enum EntityType {
  None(0, "None"),
  InventoryTransfer(1, "Inventory Transfer"),
  InventoryAdjustment(2, "Inventory Adjustment"),
  InventoryLocation(3, "Inventory Location"),
  JournalEntry(4, "Journal Entry"),
  Invoice(5, "Invoice"),
  ReturnAuthorization(6, "Return Authorization"),
  PaymentForm(7, "Payment Form"),
  Challan(8, "Challan"),
  TransferOrder(9, "Transfer Order"),
  BoxOrder(10, "Box Order"),
  Quotation(11, "Quotation"),
  CreditMemo(12, "Credit Memo"),
  VendorCredit(13, "Vendor Credit"),
  PurchaseOrder(14, "Purchase Order"),
  VendorReturnAuthorization(15, "Vendor Return Authorization"),
  Order(16, "Order"),
  ReferenceFulfill(17, "Reference Fulfill"),
  ItemReceive(18, "Item Receive"),
  ContraVoucher(19, "Contra Voucher"),
  ExpenseReport(20, "Expense Report"),
  CustomerDeposit(21, "Customer Deposit"),
  CustomerRefund(22, "Customer Refund"),
  EnterBill(23, "Enter Bill"),
  JobCard(24, "Job Card"),
  ServiceOrderBooking(25, "Service Order Booking"),
  InterRefFulfill(26, "Inter Ref Fulfill"),
  InterItemReceipt(27, "Inter Item Receipt"),
  InterTransferOrder(28, "Inter Transfer Order"),
  MedicalProfile(29, "Medical Profile"),
  Customer(30, "Customer"),
  Lead(31, "Lead"),
  Prospect(32, "Prospect"),
  Vendor(33, "Vendor"),
  PotentialCustomer(34, "Potential Customer"),
  VendorPayment(35, "Vendor Payment"),
  VendorPrepayment(36, "Vendor Prepayment"),
  Employee(37, "Employee"),
  Estimate(38, "Estimate"),
  Opportunity(39, "Opportunity"),
  Party(40, "Party"),
  Item(41, "Item"),
  Unit(42, "Unit"),
  WriteCheck(43, "Write Check"),
  Deposit(44, "Deposit"),
  TransferFund(45, "Transfer Fund"),
  Task(46, "Task"),
  Event(47, "Event"),
  CustomerReceipt(48, "Customer Receipt"),
  SalesReturn(49, "Sales Return"),
  Partner(50, "Partner"),
  SalesEstimate(51, "Sales Estimate"),
  Ledger(52, "Ledger"),
  ItemCategory(53, "Item Category");

  final int id;
  final String title;
  const EntityType(this.id, this.title);
}
